### PR TITLE
fix: unclarity of keymaps in replace-confirm window (#11)

### PR DESCRIPTION
**Pull request by chrisgrieser**
fixing this: https://github.com/cshuaimin/ssr.nvim/issues/11#issuecomment-1367356598

### CODE REVIEW

**Comment by cshuaimin** [comment]
In the https://github.com/cshuaimin/ssr.nvim/tree/bind-win branch the confirm window uses `getchar` instead of mapping, and added underlined style to the first character.

**Comment by chrisgrieser** [comment]
Oh, I see. 

I'll wait for the changes to be merged then

**Comment by chrisgrieser** [comment]
Or, I am wondering, could the PR still be merged as a temporary fix maybe until your branch is ready?

**Comment by chrisgrieser** [comment]
Thank you

**Pull request merged**
